### ISSUE TITLE
Bootloader SVL aarch64 Support

### ISSUE THREAD

**Issue by oclyke** [sparkfun/Arduino_Apollo3#105]
Continuing from https://github.com/sparkfun/Arduino_Apollo3/issues/4#issuecomment-570693213

There are two thing to address here, it seems. 

1. We could consider adding support for ```aarch64``` by default, since you've gotten it to compile. The bootlaoder problems you are experiencing should be unrelated. If you like you could make a PR to the SparkFun [Arduino Boards](https://github.com/sparkfun/Arduino_Boards) repo that includes your changes. Otherwise I can take care of it.
1. You are having bootloader troubles which can be resolved in this issue.

So regarding the bootloader...
* You seem to have the core ```v1.0.23``` installed. That comes with an updated version of the SVL loader (v5). Have you updated the bootloader on the board by using the 'Burn Bootloader' option from the Arduino Tools menu? (v5 should be backward compatible but it can't hurt to update)
* Your error appears to be a Python syntax error - potentially also caused by the difference in architecture. The executable under ```tools/artemis/linux``` was created using ```pyinstaller --onefile artemis_svl.py``` on an Ubuntu 18.04 machine. I'm not terribly familiar with the differences between linux flavors and host architectures but there may be some incompatibility. You can try two solutions:

1. Modify ```platform.txt``` so that the upload step actually calls ```python3``` to run the source code script (which you can then edit play around with to see what's going on)
  Change:
  ```tools.artemis_svl.pgm={runtime.platform.path}/tools/artemis/linux/artemis_svl```
  to:
  ```python3 {runtime.platform.path}/tools/artemis/artemis_svl.py```
1. Try using PyInstaller to generate an executable for your architecture. That would be along the lines of ```pyinstaller --onefile artemis_svl.py```

**Comment by Wenn0101** [comment]
closed due to inactivity
