### ISSUE TITLE
Artemis SVL Error Messages Incorrectly Point at Serial Port

### ISSUE THREAD

**Issue by oclyke** [sparkfun/Arduino_Apollo3#119]
As mentioned in #104 the SVL accidentally [lost a fix for exception handling](https://github.com/sparkfun/Arduino_Apollo3/commit/977cad9a3df11223d13a53225f428c08b64297e6#diff-26f4d06e142bd6a902c26fb207d67d81L338). This causes the script to suggest Serial communication errors whenever anything fails. Can be very misleading.

**Comment by nseidle** [comment]
Should be fixed in [PR 137](https://github.com/sparkfun/Arduino_Apollo3/pull/137).
