### ISSUE TITLE
reading ADC channel : sometimes incorrect readings or old readings 

### ISSUE THREAD

**Issue by paulvha** [sparkfun/Arduino_Apollo3#130]
Error 2 description
sometimes incorrect readings when reading ADC channel

Reproduce
no solid reproduction process, but happening intermittent

root cause
Interrupt reset mask is not initialized before being used
by calling am_hal_adc_interrupt_clear()

Solution
Initialize the interrupt reset mask with 0xff to reset all interrupts

###########  in ap3_analog.cpp  ################

**************routine  analogRead(uint8_t pinNumber) ******************
in the top:

change:
    uint32_t ui32IntMask;

To :
    uint32_t ui32IntMask = 0xff;

**Comment by oclyke** [comment]
@paulvha I added a commit to the existing PR for ADC order (#135) that should help with this.
