### ISSUE TITLE
Umm, the 1.1.0 core just released still seems to use the wrong compiler version

### ISSUE THREAD

**Issue by stephenf7072** [sparkfun/Arduino_Apollo3#164]
Causes all the pain when trying to print floats.  Platform.txt references gcc 2017 instead of 2018, apparently the emergency fix didn't stick.  v1.1.1 has a much nicer ring to it anyway.

References:
[https://github.com/sparkfun/Arduino_Apollo3/commit/d6997accf6f4b57908aaa6f46a0200abefe8a725](url)
[https://github.com/sparkfun/Arduino_Apollo3/pull/163](url)

**Comment by oclyke** [comment]
Thanks a bunch for spotting that. Should be fixed by:
#165 
#166 
[This update to the Arduino_Boards repo](https://github.com/sparkfun/Arduino_Boards/commit/e4422251c97b17b49f6210951653d201c294cab5)

**Comment by stephenf7072** [comment]
Yep, that's better.
