### ISSUE TITLE
Uniform Handling of Interrupts

### ISSUE THREAD

**Issue by oclyke** [sparkfun/Arduino_Apollo3#240]
As it stands definitions of peripheral ISRs is scattered all about - they are in the core, they're in libraries, they're in examples. It is a MESS. If one guy already defined your ISR then there is little hope that you can also respond to the same one...

Let's fix that. Let's make a standard way to register callbacks to all of the peripheral interrupts. There should be no strict limit on the number of registered callbacks (leave it to the user to be mindful of performance)

Seriously I won't have it. Also this could help clarify who is really in charge of the ISRs (is it mbed or Arduino?)

**Comment by Wenn0101** [comment]
Closed due to inactivity. Please create a new issue if help is still needed.
