### ISSUE TITLE
missing networking files

### ISSUE THREAD

**Issue by lpdunwell** [sparkfun/Arduino_Apollo3#244]
is there any particular reason why you still aren't packing the client.h, server.h and udp.h files? it's pretty annoying to have to copy these after an update...

**Comment by oclyke** [comment]
This is something I have not been aware of before. How are you using networking on the Apollo3?

**Comment by lpdunwell** [comment]
Ethernet2 lib...21:04, August 7, 2020, Owen <notifications@github.com>:
This is something I have not been aware of before. How are you using networking on the Apollo3?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
---Лука 光 DunwellSent from my really heavy phone

**Comment by oclyke** [comment]
Will be fixed in v2.0.0

**Comment by oclyke** [comment]
The Adafruit Ethernet2 library is deprecated
https://github.com/adafruit/Ethernet2
