### ISSUE TITLE
SPI needs setClockDivider

### ISSUE THREAD

**Issue by nseidle** [sparkfun/Arduino_Apollo3#26]
Attempting to run [SparkFun BME280](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library) library failed because 

    C:\Dropbox\Apps\Arduino\libraries\arduino_173658\src\SparkFunBME280.cpp: In member function 'uint8_t BME280::begin()':
    C:\Dropbox\Apps\Arduino\libraries\arduino_173658\src\SparkFunBME280.cpp:98:7: error: 'class 
    SPIClass' has no member named 'setClockDivider'
        SPI.setClockDivider(SPI_CLOCK_DIV32);

**Comment by nseidle** [comment]
FWIW it's not recommended for use in new projects: https://www.arduino.cc/en/Reference/SPISetClockDivider

**Comment by nseidle** [comment]
Notes to myself: we're not respecting LSB MSB settings. I believe the HAL has MSB hardcoded:

![image](https://user-images.githubusercontent.com/117102/60924287-0f5eb000-a25e-11e9-9669-1bf4296fa618.png)

Page 321 of datasheet shows bit 23 controls MSB/LSB so we should be able to manipulate it. I know there are bit wise operators in the HAL...

![image](https://user-images.githubusercontent.com/117102/60924588-c9eeb280-a25e-11e9-98f5-c4876320e8b3.png)

**Comment by nseidle** [comment]
Register access helper macros: 

![image](https://user-images.githubusercontent.com/117102/60925181-2e5e4180-a260-11e9-9610-4cabdbc22cea.png)

**Comment by nseidle** [comment]
The macro helper functions are defined in v2.2 of HAL so we don't have access to them but the AM_REGVAL is available and seems to be working.

**Comment by nseidle** [comment]
Should be fixed in PR #30.

**Comment by oclyke** [comment]
All this is taken care of now. Thanks!
