### ISSUE TITLE
version 2.0.1 is 2.9GB !!

### ISSUE THREAD

**Issue by paulvha** [sparkfun/Arduino_Apollo3#268]
Version 2.0.0 was 1.1GB  (which is already big) but version  2.0.1 is 2.9GB. HUGE !!! takes ages to download.

The reason is that .git and .github directories are included in the compressed file. .git is 1.8GB !!

Please remove those from the tar file.

regards,
Paul

**Comment by oclyke** [comment]
Gladly!
