### ISSUE TITLE
Artemis in feather footprint?

### ISSUE THREAD

**Issue by idea--list** [sparkfun/Arduino_Apollo3#27]
This is rather a HW related question:
Do you also plan a feather compatible board with the artemis chip?

**Comment by oclyke** [comment]
@idea--list Good question. Right now I am not aware of any Feather footprint plans for Artemis, however we have released a few Feather compatible boards lately. I would not rule it out -- it just might come as a priority below a few other projects. I'll make sure the idea is out there. 

FYI in the future the SparkFun forums might be a better place for comments/questions that aren't directly related to the core. Here's the link for 'Artemis Products' subforum: https://forum.sparkfun.com/viewforum.php?f=163
