### ISSUE TITLE
SPI speed

### ISSUE THREAD

**Issue by awende** [sparkfun/Arduino_Apollo3#284]
While using the HyperDisplay_KWH018ST01 examples, the Artemis module runs significantly slower than say the ESP32 module.  After connecting the oscilloscope to the SCK pin, the problem appears to be that the delay between byte transfers on the ESP32 is around 800ns, whereas on the Artemis it's around 15us:

Here's the ESP32:
![ESP32](https://user-images.githubusercontent.com/17887983/95909554-ecbe1f80-0d5b-11eb-8894-bf443191f0d7.png)

And here's the Artemis:
![Artemis](https://user-images.githubusercontent.com/17887983/95909585-fc3d6880-0d5b-11eb-920c-1a3d3f8c7478.png)

Both boards are running the exact same Example1_DisplayTest for the HyperDisplay_KWH018ST01 library

**Comment by Wenn0101** [comment]
Closed due to inactivity. Please create a new issue if help is still needed.
