### ISSUE TITLE
Same MAC address for two Artemis Thing Plus

### ISSUE THREAD

**Issue by andreh1111** [sparkfun/Arduino_Apollo3#290]
Hi,
I don't know if you can help me with this problem, but I try anyway :)
I have to use two Artemis Thing Plus in my BLE system. The problem is that the MAC address they expose is the same, so I can't connect to both at the same time. Does anyone have any idea if it is possible to change the MAC address?
Thanks a lot to anyone who will answer.

**Comment by paulvha** [comment]
had the same issue. Check out https://forum.sparkfun.com/viewtopic.php?f=183&t=54319 for a solution
regards,
Paul

**Comment by Wenn0101** [comment]
A fix for this is scheduled for v2.0.6, see https://github.com/sparkfun/Arduino_Apollo3/discussions/368 to preview release.
