### ISSUE TITLE
ArduinoBLE on Artemis Thing Plus seems not to work since v2.0.2 release

### ISSUE THREAD

**Issue by andreh1111** [sparkfun/Arduino_Apollo3#291]
Hi,
I'm using Artemis Thing Plus and the ArduinoBLE library. My firmware developed with v2.0.1 and working, no longer works after upgrading to v2.0.2.

I don't know if this can be useful, but I did some tests and BLE.begin() always return 0.

Thank you for your support :)

**Comment by Menaures** [comment]
Hi,
I experienced the same issue on the Redboard Artemis Nano. Commit 8cb68046aa722dc27d2b961cc7a10e439d77d86 is the latest version that worked for me.

**Comment by pratapppv** [comment]
Hi,
Same issue for me as well. Artemis Thing Plus seems to be getting stuck at the BLE.begin() stage which doesn't seem to be returning at all.

**Comment by Wenn0101** [comment]
fixed in latest version release
