### ISSUE TITLE
AnalogRead example in V2.0.2 always returns 0 on external analog pins

### ISSUE THREAD

**Issue by idea--list** [sparkfun/Arduino_Apollo3#304]
I know core V2.0.2 is built on top of Mbed-OS, that is why i thought i will take a look on the code and try to port it to Mbed as AnalogIn is still not implemented.

During my effort i noticed that all the different analogread functions work fine except for indexAnalogRead(). As a consequence the board can not measure voltages applied to an external pad, no matter which one i try.
I do not find the root of this bug, can anyone give some hints please?

**Comment by Wenn0101** [comment]
closed in favor of https://github.com/sparkfun/Arduino_Apollo3/issues/340
