### ISSUE TITLE
How to configure SPI pins on Sparkfun Edge?

### ISSUE THREAD

**Issue by metanav** [sparkfun/Arduino_Apollo3#31]
Which GPIOs are MOSI/MISO/SCLK?

**Comment by nseidle** [comment]
On Edge the GPIOs are labeled 3/36/38/1. The pad function map can be found [here](https://cdn.sparkfun.com/assets/learn_tutorials/9/0/9/Apollo3_Pad_Mapping.pdf). These are not mapped to SPI. Designing the Edge we used the variety of GPIO for the camera, accel, mic, and the LEDs. The remaining GPIO are broken out but they unfortunately don't support SPI. 

Please consider the variety of [Artemis carrier boards](https://www.sparkfun.com/artemis). They exposed multiple SPI and I2C ports.
