### ISSUE TITLE
Burst Mode missing from v2 core

### ISSUE THREAD

**Issue by Marsfan** [sparkfun/Arduino_Apollo3#318]
It seems that the functions `enableBurstMode()` and `disableBurstMode()` are no longer available in the v2 core for the Artemis.

**Comment by Wenn0101** [comment]
@Marsfan thanks for the report. I will look into this.

**Comment by Marsfan** [comment]
@Wenn0101 I tried calling the HAL functions, but I got some sort of stackdump error from MBED OS.

**Comment by Wenn0101** [comment]
We have more than 1 issue tracking this. Closing in favor of https://github.com/sparkfun/Arduino_Apollo3/issues/358
