### ISSUE TITLE
Missing WString.h

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#346]
I get quite many messages about missing WString.h. Suppose it is one of these 'common' headers that should be part of the core? :) .

**Comment by paulvha** [comment]
WString.h is included.....2.0.5/cores/arduino/mbed-bridge/core-api/api/deprecated BUT this folder is not included in search path. That said: looking in WString.h:   including WString.h is deprecated, for all future projects use Arduino.h instead
So apparently you can just delete an  '#include <Wstring.h>' in the source  as Arduino.h is included by default.
Regards,
Paul

**Comment by jerabaul29** [comment]
Ok, thanks! This is slightly inconvenient as it breaks some libraries, but will be able to fix it then. Thanks! :)
