### ISSUE TITLE
SoftwareSerial not working

### ISSUE THREAD

**Issue by chsmit15** [sparkfun/Arduino_Apollo3#366]
I'm on Win10 Arduino 1.8.9.  I'm using the Artemis Nano and have a project working that uses SoftwareSerial. When I upgrade to Apollo3 Boards 2.0.5 (from 1.2.1) it no longer compiles and says it can't find <SoftwareSerial.h>.

Seems it would be odd to NOT include this support when it was working in an earlier version.

**Comment by paulvha** [comment]
hi
I have created a SoftwareSerial for V2.0.6 based on the original one that was in V1.2.1. It has its limitations,described in the link, but it might still be useful for you: https://github.com/paulvha/apollo3/tree/master/SoftwareSerial
regards,
Paul

**Comment by chsmit15** [comment]
Ok, thanks
