### ISSUE TITLE
SVL permissions error present on v2.0.6

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/Arduino_Apollo3#373]
Hi folks,

After updating to v2.0.6, I experienced the same svl permissions error on both macOS Big Sur and Catalina.

However, when I tested the preview of the release by manually downloading the core and renaming it to 2.0.4, this issue didn't present itself.

After a `chmod +x svl` I can upload code successfully, but it's strange that the fix didn't seem to stick for v2.0.6. 

Would be helpful if any other macOS or Linux users could confirm this (e.g. @jerabaul29).

Cheers,
Adam

**Comment by Wenn0101** [comment]
@adamgarbo Give it another go.

I repackaged the release, and I have it working on my test machine.

**Comment by adamgarbo** [comment]
Removed and redownloaded v2.0.6 and was able to upload code on macOS Big Sur without any svl permission errors. Thanks, @Wenn0101!
