### ISSUE TITLE
progmem equivalent

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#385]
What is the recommended way to store data in a "PROGMEM equivalent" way? I saw some posts on the forum about using the "EEPROM" library but I wonder if this would be a bit unpractical (as no typing etc). Is there a way to simply add a keyword to a declaration so as to make a large array of static, constant data live natively in flash without any impact on the RAM?

**Comment by Wenn0101** [comment]
Since this was posted, there are some updated EEPROM examples that could hopefully get someone going. Let me know if you still need help with this. closing.
