### ISSUE TITLE
how to install from the board manager the v1 of the core?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#389]
It looks like only the core v2 is available on the Arduino cores, for example for the Arduino IDE2.x I get to install the core v2.0.3 to v2.0.6, but no trace of the core v1.x.x.

![Screenshot from 2021-05-08 17-55-44](https://user-images.githubusercontent.com/8382834/117545684-1c4db580-b027-11eb-85cc-3fecd3c9b24b.png)

The same is true of the Arduino IDE 1.8.13, though for a reason I ignore, I cannot take a screenshot.

Is there something I am doing wrong, or has the core v1 disappeared from the Arduino board manager?

I have some code only running on the core v1, and the core v2 is still a bit too "experimental" for some of my applications at the moment, so I (and the people I work with) need the core v1. My question / request is then: could you make sure that the latest version of the core v1 is also published and available for install?

**Comment by Wenn0101** [comment]
Hmm interesting. I still see it in Arduino 1.8.13, I wonder what the difference is in our set-up. what OS are you using?

I'll try it in the Arduino IDE 2.x

![image](https://user-images.githubusercontent.com/57247268/117554919-e94ff580-b017-11eb-8c67-29cf81aecf40.png)

**Comment by jerabaul29** [comment]
Many thanks for checking that out.

Ubuntu 20.04.

Aaah, sorry, maybe I understand: looks like I am on 1.2.1 already and that is the one I cannot see in the menu, while you are on 2.0.6 and that is the one you cannot see on the menu.

**Comment by jerabaul29** [comment]
Sorry, that may be a false alarm then. Strange, I was checking it because someone told me they could not install the 1.xx. They were probably doing something wrong another place...

**Comment by jerabaul29** [comment]
If you can confirm this then feel free to close. Sorry for the noise.
