### ISSUE TITLE
No Example of Serial Interrupts

### ISSUE THREAD

**Issue by YFNZ** [sparkfun/Arduino_Apollo3#399]
It'd be awesome if someone could add an example using serial interrupts to receive serial data onto the device.

**Comment by Wenn0101** [comment]
Thanks for the feedback, we will take a look.

**Comment by Wenn0101** [comment]
Hello, I am taking a look back at this issue to work on it. Can you explain more what you were hoping for in the example. 

The [existing serial example](https://github.com/sparkfun/Arduino_Apollo3/blob/main/libraries/Apollo3/examples/Serial/Serial.ino) uses interrupts but it all happens "under the hood". Were you hoping to be able to be able to perform logic in the interrupt yourself? were you hoping for an example that uses Serial1?

Let me know. Thanks.
-Kyle

**Comment by paulvha** [comment]
looks to me this was related to this post. https://forum.sparkfun.com/viewtopic.php?f=169&t=55742
I think the issue is solved.
regards,
Paul
