### ISSUE TITLE
meta / discussion: programming in Rust

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#408]
This is quite meta / discussion.

I have had colleagues trying to push me to have a look at Rust. For quite some time I was reluctant ("why would I learn yet another language to do the same stuff I already do in C++?"). However, after some months of advertising by them, some time spent looking at weird memory bugs, etc, I am giving it a look now on my spare time. Actually, I start to get more and more sold to it too ^^ .

My question is: are there possibilities to / have any user experience with / any suggestions regarding / programming the Artemis platform by writing some Rust instead of some C++? Any thoughts?

**Comment by Wenn0101** [comment]
Created a [discussion topic](https://github.com/sparkfun/Arduino_Apollo3/discussions/419) on this. closing the issue.
