### ISSUE TITLE
any plans to update the MCU?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#429]
It looks like Ambiq came up with a beefier Apollo 3, with in particular double the Flash and double the RAM: https://ambiq.com/apollo3-blue-plus/ .

Any hope that SF may upgrade its line of products to the beefier version some day? :) .

**Comment by Wenn0101** [comment]
At this point I don't know if we have any plans to update the processor, but I will make sure that the people in charge of making this decision know about the update.
