### ISSUE TITLE
I2S example

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#445]
Any example of I2S and how to use it?

**Comment by Wenn0101** [comment]
Sorry we don't have any I2S examples. 

I suggest checking out section 10.3 of the [Datasheet](https://cdn.sparkfun.com/assets/1/5/c/6/7/Apollo3-Blue-MCU-Datasheet_v0_15_0.pdf). And checking out the datasheet of the device you are connecting to it for more information.
