### ISSUE TITLE
adding codec 2 to a project

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#447]
I am interested in adding codec 2 for performing efficient voice encoding / decoding, see: https://github.com/drowe67/codec2 .

It seems that there is some support specifically for the ARM cores with floating point embedded, see:

> On ARM machines, setting the C Flag __EMBEDDED__ and linking with the ARM CMSIS library will improve performance on ARM-based microcontrollers. __REAL__ and FDV_ARM_MATH are additional ARM-specific options that can be set to improve performance if required, especially with OFDM modes.

Unfortunately, I am really not good at figuring out these issues around how to get some libraries to compile in the arduino framework when they are not thought for that. Anybody who has had the same need and has already done something around this? :)

**Comment by Wenn0101** [comment]
Hi @jerabaul29 unfortunately I dont have much experience with this and you didn't seem to get much help here. Perhaps try the forums, someone there might have experience with this!
