### ISSUE TITLE
add some examples of how to use the times in core v1?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Arduino_Apollo3#450]
It would be very helpful to have a few examples on how to use the timers on core v1 (guess it would be available also on core v2 in the same way, though MBedOS may already provide some high level interface to these (?) ), in particular for users who are not too good with the low level aspects and may need an example to be able to understand the datasheet.

Things like:

- call a given function at a given (high) frequency using a timer-driven ISR
- toogle a pin at a given frequency using a timer

All I can found of "high level examples" so far are: (if you have some more references, please let me know :) ):

- https://forum.sparkfun.com/viewtopic.php?t=52254
- https://forum.sparkfun.com/viewtopic.php?t=51868

It would be really amazing if there could be a couple more examples to cover these aspects :) .

**Comment by Wenn0101** [comment]
Unfortunately, I don't know if I will be able to commit the time to add more examples to the v1 core. If you are able to put together an example I would accept the pull request tho!
