### ISSUE TITLE
Broken link to CodeConventions

### ISSUE THREAD

**Issue by ArminJo** [sparkfun/Arduino_Apollo3#469]
Here https://github.com/sparkfun/Arduino_Apollo3/blob/main/docs/CONTRIBUTING.md#how-to-contribute is the broken link.
Where is it gone, I used id as a reference? 😞

**Comment by paulvha** [comment]
I just clicked on the link you provided and see the CONTRIBUTING.md. Is this still not working for you ?

regards
Paul

**Comment by ArminJo** [comment]
Hi Paul,
In the page CONTRIBUTING.md, there is a broken link https://github.com/sparkfun/Arduino_Apollo3/blob/main/docs/CODECONVENTIONS.md to CodeConventions.

**Comment by paulvha** [comment]
indeed THAT link is broken...
