### ISSUE TITLE
Serial Port Usage in Core Examples

### ISSUE THREAD

**Issue by oclyke** [sparkfun/Arduino_Apollo3#5]
### Subject of the issue
Raising this issue as a response to a compilation error I ran into with example2_serial -- "Serial1 not defined." I was compiling with Edge V2 variant, which is as of right now simply a copy of Edge which only has one serial object defined.

So we can't really guarantee that any given variant will have a particularly named serial object. 'Serial' is extremely likely, and after that it starts getting a little less clear. My suggestion would be to ```#define SERIAL_PORT Serial``` at the top of the file and in order to potentially demonstrate a secondary port ```#define SECONDARY_PORT Serial1``` with a comment explaining that you may need to replace that with another name (```SERIAL_PORT``` if you only have one port, and maybe ```mySerial``` if you've defined your own serial object on some pins that suit your needs)

As an argument against these #define statements they *may* be slightly more intimidating or confusing for beginners. 

(P.s. taking a more formal approach to suggesting this change b/c the examples have been heavily prettified as we move toward the initial release.)

**Comment by nseidle** [comment]
I think this issue has been mostly resolved as Edge 2 variant now has Serial defined.

I think the lower examples (1, 2) should use Serial and and higher/possible advanced example could benefit from #defines for the serial ports.
