### ISSUE TITLE
ATP fails to compile Blink - Unused pin def not compatible

### ISSUE THREAD

**Issue by nseidle** [sparkfun/Arduino_Apollo3#52]
ATP uses the 

    AP3_GPIO_PAD_UNUSED, //The one pad not broken out of the Apollo3 on the Artemis

in the variant file:

![image](https://user-images.githubusercontent.com/117102/63287284-3d7cda00-c277-11e9-9657-10d0f5557e09.png)

When we removed the -w compiler flag, ATP now fails to compile with the following error:
    
    C:\...\...\apollo3\0.0.0\variants\SparkFun_BlackBoard_Artemis_ATP\config\variant.cpp:77:1: error: narrowing conversion of '-1' from 'int' to 'ap3_gpio_pad_t' {aka 'unsigned char'} inside { } [-Wnarrowing]

I plan to change the header files to change UNUSED define to 255 instead of -1.

**Comment by oclyke** [comment]
Sounds like a good solution to me!
