### ISSUE TITLE
Warning: SPI function without return

### ISSUE THREAD

**Issue by nseidle** [sparkfun/Arduino_Apollo3#55]
Looks like a function `__interruptsStatus()` needs a return value:

C:\Users\user\AppData\Local\Arduino15\packages\SparkFun\hardware\apollo3\0.0.0\libraries\SPI\src\SPI.cpp: In function 'unsigned char __interruptsStatus()':
C:\Users\user\AppData\Local\Arduino15\packages\SparkFun\hardware\apollo3\0.0.0\libraries\SPI\src\SPI.cpp:133:1: warning: no return statement in function returning non-void [-Wreturn-type]

**Comment by oclyke** [comment]
This was fixed in the pull request
