### ISSUE TITLE
BLE Example doesn't compile as is

### ISSUE THREAD

**Issue by Dressner95** [sparkfun/Arduino_Apollo3#62]
### Example 8 BLE 
Does not compile in the arduino IDE

### Your workbench
* Windows 10 - Arduino IDE 1.8.10
* Redboard atremis v10
* USB C to USB A
* Powered off USB
* 

### Steps to reproduce
Try and compile the Example for the Redboard

### Needs
It asks for many files from the AmbiqSuite

**Comment by oclyke** [comment]
Are you using the latest version of the core? v1.0.11 is available through the Arduino boards manager and should fix this
